### ISSUE TITLE
scom integration bug

### ISSUE THREAD

**Issue by sulincix** [Zaryob/inary#15] opened 2019-10-08 11:12 UTC
I think scom start with inary

**Comment by Zaryob** [comment] 2019-11-16 10:30
#26

**Comment by Zaryob** [comment] 2019-11-16 10:30
#28

**Comment by Zaryob** [comment] 2019-11-16 12:03
this issue fixed in [commit](https://github.com/Zaryob/inary/commit/248485d572d57b52a8cadb124ee6500168d5f3d3)

scom service problem caused by chowning policy

**Closed by Zaryob** 2019-11-16 12:03 UTC
Labels: Critical changes, bug, enhancement
